# -*- coding: utf-8 -*-
"""tic_tac_toe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WC6bzv5AKC2yjsYsP5m95k0CjrowOQUo
"""

for i in range(10,50,4):
  print(i*i)